import React from "react";
import type { NextPage } from "next";
import Head from "next/head";

const Add: NextPage = () => {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div>react three is here</div>
        </>
    );
};

export default Add;
